use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :flambe, FlambeWeb.Endpoint,
  http: [
    port: 4000,
    protocol_options: [
      max_header_name_length: 640_000,
      max_header_value_length: 40_960_000,
      max_headers: 1_000_000
    ]
  ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    # node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
    # cd: Path.expand("../assets", __DIR__)]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :flambe, FlambeWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/flambe_web/views/.*(ex)$},
      ~r{lib/flambe_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :flambe, Flambe.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "flambe_dev",
  hostname: "localhost",
  pool_size: 10

config :flambe, Flambe.Guardian,
  issuer: "flambe",
  secret_key: "8K68whWQOJn1kvRuJ3NmgkK36GDF4Q6/Z5UMtzCK+c/Tw4BO6fU/1IH/JiMyu+C6"

import_config "dev.secret.exs"
