defmodule FlambeNextWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :flambe_next

  # The browser session is encrypted, signed, HTTP-only, and scoped to the
  # same site. Production HTTPS deployments also set Secure; HTTP prod CI
  # (PHX_URL_SCHEME=http) must not, or WebKit drops the cookie.
  #
  # Cookies without Max-Age are session cookies. iOS Safari drops those when
  # it kills the browser process (typical after switching apps), so every
  # fresh load of the SPA required logging in again.
  @session_max_age 60 * 60 * 24 * 60

  @session_options [
    store: :cookie,
    key: "_flambe_next_key",
    signing_salt: "wpvY4weL",
    encryption_salt: "eY8rV2mQ",
    http_only: true,
    same_site: "Lax",
    max_age: @session_max_age
  ]

  def session_options do
    Keyword.put(
      @session_options,
      :secure,
      Application.get_env(:flambe_next, :session_cookie_secure, false)
    )
  end

  socket "/socket", FlambeNextWeb.UserSocket,
    # The SPA has no server-rendered CSRF token to include in the WebSocket
    # handshake. Authentication still comes exclusively from the encrypted,
    # same-site session cookie, and Phoenix validates the request origin.
    websocket: [
      connect_info: [session: {__MODULE__, :session_options, []}],
      check_csrf: false,
      check_origin: true
    ],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # Local Mix :dev serves the blue flame so a tab on :4001 is
  # distinguishable from production. Vite does the same on :5173.
  if Mix.env() == :dev do
    plug :serve_dev_favicon
  end

  plug Plug.Static,
    at: "/",
    from: :flambe_next,
    gzip: not code_reloading?,
    only: FlambeNextWeb.static_paths(),
    only_matching: ~w(favicon),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :flambe_next
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session
  plug FlambeNextWeb.Router

  defp session(conn, _opts) do
    opts = Plug.Session.init(session_options())
    Plug.Session.call(conn, opts)
  end

  if Mix.env() == :dev do
    defp serve_dev_favicon(%Plug.Conn{path_info: path_info} = conn, _opts)
         when path_info in [["favicon.png"], ["favicon.ico"]] do
      file = Application.app_dir(:flambe_next, "priv/static/favicon_dev.png")

      conn
      |> Plug.Conn.put_resp_content_type("image/png")
      |> Plug.Conn.send_file(200, file)
      |> Plug.Conn.halt()
    end

    defp serve_dev_favicon(conn, _opts), do: conn
  end
end
