// flow-typed signature: 69269982cee9bf49ab5f9c8d0b010fb1
// flow-typed version: <<STUB>>/multiparty_v^4.1.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multiparty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multiparty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'multiparty/index' {
  declare module.exports: $Exports<'multiparty'>;
}
declare module 'multiparty/index.js' {
  declare module.exports: $Exports<'multiparty'>;
}
