import type { Activity } from '../types/Activity';
import type { Category } from '../types/Category';
import type { EntityId } from '../types/ids';
import type { Thread } from '../types/Thread';
import type { TraceEvent } from '../types/TraceEvent';
import type { AppChartFixture } from './fixtureTrace';

const DAY = 24 * 60 * 60 * 1000;
const YEAR = 365.2425 * DAY;

const categories: Category[] = [
  { id: 1, name: 'earth system', color_background: '#7dd3fc', color_text: '#082f49' },
  { id: 2, name: 'evolution', color_background: '#86efac', color_text: '#052e16' },
  { id: 3, name: 'turnover / extinction', color_background: '#fda4af', color_text: '#4c0519' },
  { id: 4, name: 'subsistence / settlement', color_background: '#fde68a', color_text: '#422006' },
  { id: 5, name: 'state / empire', color_background: '#c4b5fd', color_text: '#2e1065' },
  { id: 6, name: 'exchange / ideas', color_background: '#f9a8d4', color_text: '#500724' },
  { id: 7, name: 'technology / energy', color_background: '#fdba74', color_text: '#431407' },
];

type SpanSpec = {
  id: number;
  thread: number;
  name: string;
  startYearsAgo: number;
  endYearsAgo: number;
  category: EntityId;
  parentId?: number;
  description?: string;
};

function yearsAgo(now: number, years: number): number {
  return now - years * YEAR;
}

function thread(id: number, name: string, rank: number): Thread {
  return { id, name, rank, collapsed: false };
}

const threads: Thread[] = [
  thread(1, 'Earth system 🌍', 0),
  thread(2, 'Life & faunal turnover 🧬', 1),
  thread(3, 'Hominin lineages 🦴', 2),
  thread(4, 'Subsistence & settlement 🌾', 3),
  thread(5, 'States & empires 🏛️', 4),
  thread(6, 'Exchange, belief & knowledge 🛶', 5),
  thread(7, 'Technology & energy ⚙️', 6),
];

const spans: SpanSpec[] = [
  // Earth system: the slow background field that repeatedly changes the option set.
  {
    id: 100,
    thread: 1,
    name: 'Cenozoic cooling world',
    startYearsAgo: 66_000_000,
    endYearsAgo: 2_580_000,
    category: 1,
    description: 'Long cooling trend from the warm early Cenozoic toward a planet with large permanent ice sheets and stronger climate gradients.',
  },
  {
    id: 101,
    thread: 1,
    name: 'Paleocene–Eocene Thermal Maximum',
    startYearsAgo: 56_000_000,
    endYearsAgo: 55_850_000,
    category: 1,
    parentId: 100,
    description: 'A geologically abrupt carbon-release and warming event that reorganized ecosystems and ocean chemistry.',
  },
  {
    id: 102,
    thread: 1,
    name: 'Antarctic glaciation locks in',
    startYearsAgo: 34_000_000,
    endYearsAgo: 33_000_000,
    category: 1,
    parentId: 100,
    description: 'Major expansion of Antarctic ice near the Eocene–Oligocene transition.',
  },
  {
    id: 103,
    thread: 1,
    name: 'Quaternary ice-age regime',
    startYearsAgo: 2_580_000,
    endYearsAgo: 11_700,
    category: 1,
    description: 'Repeated glacial–interglacial cycling becomes the dominant environmental rhythm experienced by later hominins.',
  },
  {
    id: 104,
    thread: 1,
    name: 'Mid-Pleistocene Transition',
    startYearsAgo: 1_250_000,
    endYearsAgo: 700_000,
    category: 1,
    parentId: 103,
    description: 'Glacial cycles shift toward longer, larger-amplitude ~100,000-year pacing.',
  },
  {
    id: 105,
    thread: 1,
    name: 'Last glacial cycle',
    startYearsAgo: 115_000,
    endYearsAgo: 11_700,
    category: 1,
    parentId: 103,
    description: 'The final full glacial cycle before the Holocene, including the Last Glacial Maximum and deglaciation.',
  },
  {
    id: 106,
    thread: 1,
    name: 'Holocene relatively stable climate',
    startYearsAgo: 11_700,
    endYearsAgo: 0,
    category: 1,
    description: 'Warm interglacial interval within which agriculture, cities, states, and industrial society expand.',
  },
  {
    id: 107,
    thread: 1,
    name: '8.2 ka cooling event',
    startYearsAgo: 8_250,
    endYearsAgo: 8_050,
    category: 1,
    parentId: 106,
    description: 'Abrupt cooling episode associated with meltwater discharge into the North Atlantic.',
  },
  {
    id: 108,
    thread: 1,
    name: '4.2 ka aridification episode',
    startYearsAgo: 4_250,
    endYearsAgo: 3_950,
    category: 1,
    parentId: 106,
    description: 'A broad interval of climatic stress visible in several regions; links to individual political collapses are debated and region-specific.',
  },
  {
    id: 109,
    thread: 1,
    name: 'Little Ice Age climate interval',
    startYearsAgo: 700,
    endYearsAgo: 170,
    category: 1,
    parentId: 106,
    description: 'Multi-century interval of generally cooler conditions in parts of the Northern Hemisphere, with strong regional variability.',
  },
  {
    id: 110,
    thread: 1,
    name: 'Human-driven greenhouse forcing',
    startYearsAgo: 276,
    endYearsAgo: 0,
    category: 1,
    parentId: 106,
    description: 'Industrial-scale fossil carbon emissions increasingly alter atmospheric composition and global energy balance.',
  },

  // Life: broad radiations plus selected charismatic turnovers that make deep time legible.
  {
    id: 200,
    thread: 2,
    name: 'K–Pg mass extinction',
    startYearsAgo: 66_050_000,
    endYearsAgo: 65_900_000,
    category: 3,
    description: 'Impact-driven mass extinction ends non-avian dinosaurs and opens ecological space for surviving lineages.',
  },
  {
    id: 201,
    thread: 2,
    name: 'Placental mammal radiation',
    startYearsAgo: 66_000_000,
    endYearsAgo: 50_000_000,
    category: 2,
    description: 'Rapid diversification of mammals into many ecological roles during the early Cenozoic.',
  },
  {
    id: 202,
    thread: 2,
    name: 'Early whales move into the sea',
    startYearsAgo: 50_000_000,
    endYearsAgo: 34_000_000,
    category: 2,
    description: 'Cetacean ancestors transition from terrestrial artiodactyl relatives to fully aquatic whales.',
  },
  {
    id: 203,
    thread: 2,
    name: 'Crown primates diversify',
    startYearsAgo: 55_000_000,
    endYearsAgo: 0,
    category: 2,
    description: 'Primates diversify through changing forest worlds; this lineage eventually contains apes and hominins.',
  },
  {
    id: 204,
    thread: 2,
    name: 'Apes diversify',
    startYearsAgo: 23_000_000,
    endYearsAgo: 0,
    category: 2,
    parentId: 203,
    description: 'Hominoids emerge and diversify in the Miocene; only a small set of lineages survive today.',
  },
  {
    id: 205,
    thread: 2,
    name: 'Proboscideans spread and diversify',
    startYearsAgo: 60_000_000,
    endYearsAgo: 0,
    category: 2,
    description: 'The elephant lineage expands into many forms across Africa and later much of Eurasia and the Americas.',
  },
  {
    id: 206,
    thread: 2,
    name: 'Woolly mammoth',
    startYearsAgo: 800_000,
    endYearsAgo: 4_000,
    category: 3,
    parentId: 205,
    description: 'Cold-adapted mammoths flourish across northern Eurasia and North America, then disappear except for late island refugia.',
  },
  {
    id: 207,
    thread: 2,
    name: 'Smilodon saber-toothed cats',
    startYearsAgo: 2_500_000,
    endYearsAgo: 10_000,
    category: 3,
    description: 'A successful American predator lineage that vanishes near the end-Pleistocene megafaunal turnover.',
  },
  {
    id: 208,
    thread: 2,
    name: 'Giant ground sloths',
    startYearsAgo: 5_300_000,
    endYearsAgo: 10_000,
    category: 3,
    description: 'Large terrestrial sloths spread through the Americas and mostly disappear near the end of the Pleistocene.',
  },
  {
    id: 209,
    thread: 2,
    name: 'Late-Pleistocene megafaunal losses',
    startYearsAgo: 50_000,
    endYearsAgo: 4_000,
    category: 3,
    description: 'Staggered extinction pulse affecting many large-bodied animals; climate change and human impacts vary in importance by region.',
  },

  // Hominins: overlapping branches, not a ladder.
  {
    id: 300,
    thread: 3,
    name: 'Hominin radiation',
    startYearsAgo: 7_000_000,
    endYearsAgo: 0,
    category: 2,
    description: 'A branching radiation after the human–chimpanzee lineage split; the sequence is not a simple ancestor-to-descendant ladder.',
  },
  {
    id: 301,
    thread: 3,
    name: 'Sahelanthropus-grade early hominins',
    startYearsAgo: 7_000_000,
    endYearsAgo: 6_000_000,
    category: 2,
    parentId: 300,
  },
  {
    id: 302,
    thread: 3,
    name: 'Ardipithecus',
    startYearsAgo: 5_800_000,
    endYearsAgo: 4_400_000,
    category: 2,
    parentId: 300,
  },
  {
    id: 303,
    thread: 3,
    name: 'Australopithecines',
    startYearsAgo: 4_200_000,
    endYearsAgo: 1_900_000,
    category: 2,
    parentId: 300,
    description: 'Multiple bipedal hominin species thrive in Africa before and during the emergence of genus Homo.',
  },
  {
    id: 304,
    thread: 3,
    name: 'Homo habilis / early Homo',
    startYearsAgo: 2_400_000,
    endYearsAgo: 1_400_000,
    category: 2,
    parentId: 300,
  },
  {
    id: 305,
    thread: 3,
    name: 'Homo erectus / ergaster',
    startYearsAgo: 1_900_000,
    endYearsAgo: 110_000,
    category: 2,
    parentId: 300,
    description: 'Long-lived, geographically expansive Homo lineage associated with major changes in body plan, mobility, and technology.',
  },
  {
    id: 306,
    thread: 3,
    name: 'Middle-Pleistocene Homo',
    startYearsAgo: 700_000,
    endYearsAgo: 200_000,
    category: 2,
    parentId: 300,
    description: 'Diverse populations often grouped under labels such as H. heidelbergensis; taxonomy remains contested.',
  },
  {
    id: 307,
    thread: 3,
    name: 'Neanderthals',
    startYearsAgo: 430_000,
    endYearsAgo: 40_000,
    category: 3,
    parentId: 300,
    description: 'A Eurasian human lineage with complex technology and repeated gene flow with H. sapiens.',
  },
  {
    id: 308,
    thread: 3,
    name: 'Denisovan populations',
    startYearsAgo: 300_000,
    endYearsAgo: 50_000,
    category: 3,
    parentId: 300,
    description: 'Genetically identified sister populations to Neanderthals; fossil range and chronology remain comparatively sparse.',
  },
  {
    id: 309,
    thread: 3,
    name: 'Homo sapiens',
    startYearsAgo: 300_000,
    endYearsAgo: 0,
    category: 2,
    parentId: 300,
    description: 'Our species emerges in Africa from structured populations and later expands globally while exchanging genes with other Homo lineages.',
  },
  {
    id: 310,
    thread: 3,
    name: 'Major sapiens expansion beyond Africa',
    startYearsAgo: 75_000,
    endYearsAgo: 45_000,
    category: 2,
    parentId: 309,
  },
  {
    id: 311,
    thread: 3,
    name: 'Peopling of Sahul',
    startYearsAgo: 65_000,
    endYearsAgo: 45_000,
    category: 2,
    parentId: 309,
    description: 'Humans cross water gaps into the combined Ice Age continent of Australia–New Guinea.',
  },
  {
    id: 312,
    thread: 3,
    name: 'Peopling of the Americas',
    startYearsAgo: 23_000,
    endYearsAgo: 13_000,
    category: 2,
    parentId: 309,
    description: 'Human populations enter and rapidly spread through the Americas; exact routes and earliest dates remain active research topics.',
  },

  // Subsistence and settlement: transitions are mosaics, not one switch.
  {
    id: 400,
    thread: 4,
    name: 'Foraging lifeways dominate',
    startYearsAgo: 300_000,
    endYearsAgo: 10_000,
    category: 4,
    description: 'Most human communities rely on mobile or semi-sedentary hunting, gathering, fishing, and landscape management.',
  },
  {
    id: 401,
    thread: 4,
    name: 'Dense late-Pleistocene cultural networks',
    startYearsAgo: 50_000,
    endYearsAgo: 11_700,
    category: 4,
    parentId: 400,
    description: 'Expanding symbolic traditions, long-distance exchange, specialized technologies, and regionally dense social networks.',
  },
  {
    id: 402,
    thread: 4,
    name: 'Agricultural mosaics',
    startYearsAgo: 11_700,
    endYearsAgo: 0,
    category: 4,
    description: 'Domestication and food production emerge independently in several regions, often alongside continued foraging for millennia.',
  },
  {
    id: 403,
    thread: 4,
    name: 'Southwest Asian domestication',
    startYearsAgo: 11_700,
    endYearsAgo: 9_000,
    category: 4,
    parentId: 402,
    description: 'Cultivation and herding intensify across the Fertile Crescent through a long, uneven transition.',
  },
  {
    id: 404,
    thread: 4,
    name: 'Yangtze & Yellow River domestication',
    startYearsAgo: 10_000,
    endYearsAgo: 7_000,
    category: 4,
    parentId: 402,
    description: 'Rice and millet cultivation develop in multiple East Asian centers.',
  },
  {
    id: 405,
    thread: 4,
    name: 'New Guinea highlands cultivation',
    startYearsAgo: 10_000,
    endYearsAgo: 7_000,
    category: 4,
    parentId: 402,
  },
  {
    id: 406,
    thread: 4,
    name: 'Mesoamerican domestication',
    startYearsAgo: 9_000,
    endYearsAgo: 4_000,
    category: 4,
    parentId: 402,
    description: 'Long domestication trajectories eventually produce maize-centered agricultural systems among other crops.',
  },
  {
    id: 407,
    thread: 4,
    name: 'Andean domestication systems',
    startYearsAgo: 8_000,
    endYearsAgo: 4_000,
    category: 4,
    parentId: 402,
  },
  {
    id: 408,
    thread: 4,
    name: 'Sahel & West African domestication',
    startYearsAgo: 5_000,
    endYearsAgo: 3_000,
    category: 4,
    parentId: 402,
  },
  {
    id: 409,
    thread: 4,
    name: 'Urban systems become recurrent',
    startYearsAgo: 6_000,
    endYearsAgo: 0,
    category: 4,
    description: 'Large, dense settlements repeatedly emerge, disappear, and re-form in multiple world regions.',
  },
  {
    id: 410,
    thread: 4,
    name: 'Uruk urban expansion',
    startYearsAgo: 5_900,
    endYearsAgo: 5_100,
    category: 4,
    parentId: 409,
  },
  {
    id: 411,
    thread: 4,
    name: 'Indus urban phase',
    startYearsAgo: 4_800,
    endYearsAgo: 3_900,
    category: 4,
    parentId: 409,
  },
  {
    id: 412,
    thread: 4,
    name: 'Mesoamerican urban traditions',
    startYearsAgo: 3_100,
    endYearsAgo: 500,
    category: 4,
    parentId: 409,
    description: 'Successive Olmec, Maya, central Mexican, and other urban systems rise and transform across millennia.',
  },

  // States & empires: deliberately polycentric, with overlapping regional systems.
  {
    id: 500,
    thread: 5,
    name: 'Early territorial states',
    startYearsAgo: 5_500,
    endYearsAgo: 3_000,
    category: 5,
    description: 'Taxation, writing, standing institutions, and territorial rule become durable in several regions, though never universal.',
  },
  {
    id: 501,
    thread: 5,
    name: 'Sumerian city-state system',
    startYearsAgo: 5_526,
    endYearsAgo: 4_360,
    category: 5,
    parentId: 500,
  },
  {
    id: 502,
    thread: 5,
    name: 'Akkadian Empire',
    startYearsAgo: 4_360,
    endYearsAgo: 4_180,
    category: 5,
    parentId: 500,
  },
  {
    id: 503,
    thread: 5,
    name: 'Old Kingdom Egypt',
    startYearsAgo: 4_712,
    endYearsAgo: 4_207,
    category: 5,
    parentId: 500,
  },
  {
    id: 504,
    thread: 5,
    name: 'New Kingdom Egypt',
    startYearsAgo: 3_576,
    endYearsAgo: 3_096,
    category: 5,
    parentId: 500,
  },
  {
    id: 505,
    thread: 5,
    name: 'Shang polity',
    startYearsAgo: 3_626,
    endYearsAgo: 3_072,
    category: 5,
    parentId: 500,
  },
  {
    id: 506,
    thread: 5,
    name: 'Zhou political order',
    startYearsAgo: 3_072,
    endYearsAgo: 2_282,
    category: 5,
    description: 'A long Chinese political tradition spanning Western Zhou, fragmentation, and the Warring States era.',
  },
  {
    id: 507,
    thread: 5,
    name: 'Neo-Assyrian Empire',
    startYearsAgo: 2_937,
    endYearsAgo: 2_635,
    category: 5,
  },
  {
    id: 508,
    thread: 5,
    name: 'Achaemenid Persian Empire',
    startYearsAgo: 2_576,
    endYearsAgo: 2_356,
    category: 5,
    description: 'A large, administratively integrated empire linking the eastern Mediterranean, Egypt, Mesopotamia, Iran, and Central/South Asian frontiers.',
  },
  {
    id: 509,
    thread: 5,
    name: 'Macedonian & Hellenistic expansion',
    startYearsAgo: 2_362,
    endYearsAgo: 2_220,
    category: 5,
  },
  {
    id: 510,
    thread: 5,
    name: 'Maurya Empire',
    startYearsAgo: 2_348,
    endYearsAgo: 2_211,
    category: 5,
  },
  {
    id: 511,
    thread: 5,
    name: 'Qin unification',
    startYearsAgo: 2_247,
    endYearsAgo: 2_232,
    category: 5,
  },
  {
    id: 512,
    thread: 5,
    name: 'Han Empire',
    startYearsAgo: 2_228,
    endYearsAgo: 1_806,
    category: 5,
  },
  {
    id: 513,
    thread: 5,
    name: 'Roman Republic → Empire in the Mediterranean',
    startYearsAgo: 2_535,
    endYearsAgo: 1_550,
    category: 5,
    description: 'Roman power expands from an Italian republic into an imperial Mediterranean system; the western imperial government ends in the fifth century CE.',
  },
  {
    id: 514,
    thread: 5,
    name: 'Sasanian Empire',
    startYearsAgo: 1_802,
    endYearsAgo: 1_375,
    category: 5,
  },
  {
    id: 515,
    thread: 5,
    name: 'Byzantine / Eastern Roman Empire',
    startYearsAgo: 1_696,
    endYearsAgo: 573,
    category: 5,
  },
  {
    id: 516,
    thread: 5,
    name: 'Early Islamic caliphates',
    startYearsAgo: 1_394,
    endYearsAgo: 768,
    category: 5,
    description: 'Rashidun, Umayyad, and Abbasid-centered imperial systems transform Afro-Eurasian political and commercial networks.',
  },
  {
    id: 517,
    thread: 5,
    name: 'Tang Empire',
    startYearsAgo: 1_408,
    endYearsAgo: 1_119,
    category: 5,
  },
  {
    id: 518,
    thread: 5,
    name: 'Song state',
    startYearsAgo: 1_066,
    endYearsAgo: 747,
    category: 5,
  },
  {
    id: 519,
    thread: 5,
    name: 'Mongol imperial system',
    startYearsAgo: 820,
    endYearsAgo: 658,
    category: 5,
    description: 'A rapidly expanding steppe empire fragments into successor khanates while preserving unusually strong trans-Eurasian connections.',
  },
  {
    id: 520,
    thread: 5,
    name: 'Mali Empire',
    startYearsAgo: 791,
    endYearsAgo: 426,
    category: 5,
  },
  {
    id: 521,
    thread: 5,
    name: 'Ottoman Empire',
    startYearsAgo: 727,
    endYearsAgo: 104,
    category: 5,
  },
  {
    id: 522,
    thread: 5,
    name: 'Ming → Qing imperial order',
    startYearsAgo: 658,
    endYearsAgo: 114,
    category: 5,
    description: 'Successive Ming and Qing dynasties govern a large East Asian agrarian empire through major demographic and commercial expansion.',
  },
  {
    id: 523,
    thread: 5,
    name: 'Aztec Triple Alliance',
    startYearsAgo: 598,
    endYearsAgo: 505,
    category: 5,
  },
  {
    id: 524,
    thread: 5,
    name: 'Inca Empire',
    startYearsAgo: 588,
    endYearsAgo: 493,
    category: 5,
  },
  {
    id: 525,
    thread: 5,
    name: 'Mughal Empire',
    startYearsAgo: 500,
    endYearsAgo: 169,
    category: 5,
  },
  {
    id: 526,
    thread: 5,
    name: 'European overseas empires',
    startYearsAgo: 611,
    endYearsAgo: 60,
    category: 5,
    description: 'Overlapping Portuguese, Spanish, Dutch, French, British, Belgian and other colonial systems build global territorial and maritime empires; decolonization accelerates after 1945.',
  },
  {
    id: 527,
    thread: 5,
    name: 'Post-1945 sovereign-state order',
    startYearsAgo: 81,
    endYearsAgo: 0,
    category: 5,
    description: 'Decolonization and international institutions produce a near-global system of formally sovereign states, though power remains highly unequal.',
  },

  // Exchange and ideas: connective tissue across political borders.
  {
    id: 600,
    thread: 6,
    name: 'Bronze Age interregional exchange',
    startYearsAgo: 5_300,
    endYearsAgo: 3_200,
    category: 6,
    description: 'Metals, luxury goods, technologies, and diplomatic practices connect eastern Mediterranean, Near Eastern, and adjacent societies.',
  },
  {
    id: 601,
    thread: 6,
    name: 'Axial-age philosophical & religious traditions',
    startYearsAgo: 2_800,
    endYearsAgo: 2_200,
    category: 6,
    description: 'A loose comparative label for major intellectual and religious developments in parts of Greece, Israel/Judah, Iran, India, and China; not a single coordinated event.',
  },
  {
    id: 602,
    thread: 6,
    name: 'Silk Road network phase',
    startYearsAgo: 2_160,
    endYearsAgo: 573,
    category: 6,
    description: 'Changing caravan and oasis networks link East Asia, Central Asia, the Middle East, and Mediterranean markets; never one continuous road.',
  },
  {
    id: 603,
    thread: 6,
    name: 'Indian Ocean monsoon trade system',
    startYearsAgo: 2_300,
    endYearsAgo: 450,
    category: 6,
    description: 'Seasonal wind knowledge supports durable maritime exchange linking eastern Africa, Arabia, South Asia, Southeast Asia, and China.',
  },
  {
    id: 604,
    thread: 6,
    name: 'Trans-Saharan trade networks',
    startYearsAgo: 1_300,
    endYearsAgo: 450,
    category: 6,
  },
  {
    id: 605,
    thread: 6,
    name: 'Islamicate scholarly networks',
    startYearsAgo: 1_275,
    endYearsAgo: 600,
    category: 6,
    description: 'Arabic- and Persian-language scholarly worlds connect institutions and texts from Iberia and North Africa to Central and South Asia.',
  },
  {
    id: 606,
    thread: 6,
    name: 'Mongol-era trans-Eurasian integration',
    startYearsAgo: 820,
    endYearsAgo: 650,
    category: 6,
    parentId: 602,
  },
  {
    id: 607,
    thread: 6,
    name: 'Movable-type print cultures expand',
    startYearsAgo: 986,
    endYearsAgo: 0,
    category: 6,
    description: 'Movable type develops in East Asia centuries before Gutenberg; mass print later scales sharply in Europe and elsewhere.',
  },
  {
    id: 608,
    thread: 6,
    name: 'Columbian Exchange',
    startYearsAgo: 534,
    endYearsAgo: 326,
    category: 6,
    description: 'Plants, animals, pathogens, people, and commodities move between Afro-Eurasia and the Americas at unprecedented scale.',
  },
  {
    id: 609,
    thread: 6,
    name: 'Atlantic slave trade',
    startYearsAgo: 526,
    endYearsAgo: 159,
    category: 6,
    description: 'Forced transatlantic deportation of millions of Africans becomes a central institution of Atlantic economies and empires.',
  },
  {
    id: 610,
    thread: 6,
    name: 'Experimental scientific institutions',
    startYearsAgo: 426,
    endYearsAgo: 0,
    category: 6,
    description: 'Print, correspondence, academies, instrumentation, and increasingly formalized experimentation create self-reinforcing knowledge networks.',
  },
  {
    id: 611,
    thread: 6,
    name: 'Global telecommunications',
    startYearsAgo: 176,
    endYearsAgo: 0,
    category: 6,
    description: 'Telegraphy, telephony, radio, satellites, fiber optics, and packet networks progressively collapse communication latency.',
  },

  // Technology and energy: long-lived tool regimes, then the fossil-energy discontinuity.
  {
    id: 700,
    thread: 7,
    name: 'Oldowan stone-tool traditions',
    startYearsAgo: 2_600_000,
    endYearsAgo: 1_700_000,
    category: 7,
  },
  {
    id: 701,
    thread: 7,
    name: 'Acheulean tool traditions',
    startYearsAgo: 1_760_000,
    endYearsAgo: 130_000,
    category: 7,
    description: 'Long-lived bifacial stone-tool traditions spread across much of Africa and Eurasia.',
  },
  {
    id: 702,
    thread: 7,
    name: 'Prepared-core technologies',
    startYearsAgo: 300_000,
    endYearsAgo: 40_000,
    category: 7,
  },
  {
    id: 703,
    thread: 7,
    name: 'Metallurgical economies',
    startYearsAgo: 7_000,
    endYearsAgo: 0,
    category: 7,
    description: 'Copper, bronze, iron, steel, and later industrial metallurgy reshape tools, warfare, infrastructure, and energy systems.',
  },
  {
    id: 704,
    thread: 7,
    name: 'Bronze technology systems',
    startYearsAgo: 5_500,
    endYearsAgo: 3_200,
    category: 7,
    parentId: 703,
  },
  {
    id: 705,
    thread: 7,
    name: 'Iron & steel technology systems',
    startYearsAgo: 3_200,
    endYearsAgo: 0,
    category: 7,
    parentId: 703,
  },
  {
    id: 706,
    thread: 7,
    name: 'Gunpowder weapons spread',
    startYearsAgo: 1_025,
    endYearsAgo: 0,
    category: 7,
    description: 'Gunpowder emerges in China and gradually transforms fortification, naval warfare, and state military capacity across Eurasia.',
  },
  {
    id: 707,
    thread: 7,
    name: 'Fossil-energy industrialization',
    startYearsAgo: 266,
    endYearsAgo: 0,
    category: 7,
    description: 'Coal, then oil and gas, multiply the energy throughput available to production, transport, agriculture, and war.',
  },
  {
    id: 708,
    thread: 7,
    name: 'Steam power scales',
    startYearsAgo: 266,
    endYearsAgo: 126,
    category: 7,
    parentId: 707,
  },
  {
    id: 709,
    thread: 7,
    name: 'Electrification',
    startYearsAgo: 146,
    endYearsAgo: 0,
    category: 7,
    parentId: 707,
  },
  {
    id: 710,
    thread: 7,
    name: 'Internal-combustion transport',
    startYearsAgo: 140,
    endYearsAgo: 0,
    category: 7,
    parentId: 707,
  },
  {
    id: 711,
    thread: 7,
    name: 'Electronic computing',
    startYearsAgo: 86,
    endYearsAgo: 0,
    category: 7,
    parentId: 707,
  },
  {
    id: 712,
    thread: 7,
    name: 'Internet-scale networking',
    startYearsAgo: 36,
    endYearsAgo: 0,
    category: 7,
    parentId: 711,
  },
];

function makeActivity(spec: SpanSpec): Activity {
  const owner = threads.find(candidate => candidate.id === spec.thread);
  if (!owner) throw new Error(`Missing thread ${spec.thread}`);

  return {
    id: spec.id,
    name: spec.name,
    description: spec.description,
    categories: [spec.category],
    parent_id: spec.parentId ?? null,
    thread_id: owner.id,
    thread: owner,
  };
}

export function createDeepTimeHistoryFixture(now = Date.now()): AppChartFixture {
  let eventId = 80_000;
  const events: TraceEvent[] = spans.flatMap(spec => {
    const activity = makeActivity(spec);
    return [
      {
        id: eventId++,
        timestamp: yearsAgo(now, spec.startYearsAgo),
        phase: 'B' as const,
        activity,
      },
      {
        id: eventId++,
        timestamp: yearsAgo(now, spec.endYearsAgo),
        phase: 'E' as const,
        activity,
      },
    ];
  }).sort((left, right) => (
    left.timestamp - right.timestamp
    || String(left.id).localeCompare(String(right.id))
  ));

  return {
    traceId: 66_000,
    traceName: 'Deep time: life, humans, and empire',
    threads,
    categories,
    events,
    attentionShifts: [
      { thread_id: 1, timestamp: yearsAgo(now, 66_000_000) },
      { thread_id: 2, timestamp: yearsAgo(now, 55_000_000) },
      { thread_id: 3, timestamp: yearsAgo(now, 7_000_000) },
      { thread_id: 4, timestamp: yearsAgo(now, 11_700) },
      { thread_id: 5, timestamp: yearsAgo(now, 5_500) },
      { thread_id: 6, timestamp: yearsAgo(now, 2_800) },
      { thread_id: 7, timestamp: yearsAgo(now, 266) },
    ],
  };
}

export const DEEP_TIME_YEARS = 66_000_000;
export const DEEP_TIME_YEAR_MS = YEAR;
