// Incremental TypeScript contract for the Flow action module. Expand this as
// reducers and action creators are migrated.
export const ACTIVITY_END: string;
export const ACTIVITY_RESUME: string;
export const ACTIVITY_RESURRECT: string;
export const ACTIVITY_SUSPEND: string;
export const BLOCK_FOCUS: string;
export const SETTING_TOGGLE: string;
export const TOAST_CREATE: string;
export const TOAST_POP: string;
export const SEARCH: string;
export const SEARCH_RESULT: string;
export const SEARCH_MATCH_INCREMENT_RESULT: string;
export const SEARCH_BLOCK_INCREMENT_RESULT: string;
export const SET_THREAD_INCLUDE_LIST: string;
export const SET_THREAD_EXCLUDE_LIST: string;
export const ATTENTION_SHIFT: string;
export const CATEGORY_CREATE: string;
export const CATEGORY_UPDATE: string;
export const MANTRA_CREATE: string;
export const TODO_BEGIN: string;
export const TODO_CREATE: string;
export const TRACE_DELETE: string;
export const TRACE_CREATE: string;
export const USER_FETCH: string;
export const SEARCH_TERMS_EVENT: string;
export const TABS_EVENT: string;
export const KEY_DOWN: string;
export const KEY_UP: string;
export function createTrace(name: string): { type: string; name: string };
