defmodule FlambeNextWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :flambe_next

  # The browser session is encrypted, signed, HTTP-only, and scoped to the
  # same site. Production deployments additionally require HTTPS transport.
  @session_options [
    store: :cookie,
    key: "_flambe_next_key",
    signing_salt: "wpvY4weL",
    encryption_salt: "eY8rV2mQ",
    http_only: true,
    same_site: "Lax",
    secure: Application.compile_env(:flambe_next, :session_cookie_secure, false)
  ]

  socket "/socket", FlambeNextWeb.UserSocket,
    # The SPA has no server-rendered CSRF token to include in the WebSocket
    # handshake. Authentication still comes exclusively from the encrypted,
    # same-site session cookie, and Phoenix validates the request origin.
    websocket: [
      connect_info: [session: @session_options],
      check_csrf: false,
      check_origin: true
    ],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :flambe_next,
    gzip: not code_reloading?,
    only: FlambeNextWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :flambe_next
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FlambeNextWeb.Router
end
